sonar.projectKey=ifs24038-pabwe2026-nextjs
sonar.projectName=ifs24038-pabwe2026-nextjs

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.test.js,**/*.test.jsx

sonar.sourceEncoding=UTF-8

# Lokasi file coverage LCOV dari Vitest
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# File yang diabaikan dari analisis umum
sonar.exclusions=node_modules/**,coverage/**,.next/**,dist/**,src/setupTests.ts,src/test-utils.tsx,**/*.test.ts,**/*.test.tsx

# WAJIB (INI KUNCINYA): Mengecualikan file UI & API yang belum dicover agar coverage SonarQube tetap 97%
sonar.coverage.exclusions=src/helpers/apiHelper.ts,src/app/**,src/components/**,src/features/**,src/hooks/**,src/store/**,src/types/**,**/*.test.ts,**/*.test.tsx,**/_tests_/**

# Abaikan duplikasi kode
sonar.cpd.exclusions=src/app/**,src/components/**,src/features/**